
// This file has been generated by the GUI designer. Do not modify.
namespace TesteUnix
{
	public partial class Principal
	{
		private global::Gtk.VBox vbox1;
		private global::TesteUnix.Grid grid1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TesteUnix.Principal
			this.Name = "TesteUnix.Principal";
			this.Title = global::Mono.Unix.Catalog.GetString ("Principal");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child TesteUnix.Principal.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.grid1 = new global::TesteUnix.Grid ();
			this.grid1.Events = ((global::Gdk.EventMask)(256));
			this.grid1.Name = "grid1";
			this.vbox1.Add (this.grid1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.grid1]));
			w1.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
