
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox4;
	private global::Gtk.Button button138;
	private global::Gtk.ComboBox combobox1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView tree;
	private global::TesteUnix.WidList widlist1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button138 = new global::Gtk.Button ();
		this.button138.CanFocus = true;
		this.button138.Name = "button138";
		this.button138.UseUnderline = true;
		this.button138.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox4.Add (this.button138);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button138]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("C#"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("VB"));
		this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("C++"));
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 0;
		this.vbox4.Add (this.combobox1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.combobox1]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tree = new global::Gtk.TreeView ();
		this.tree.CanFocus = true;
		this.tree.Name = "tree";
		this.GtkScrolledWindow.Add (this.tree);
		this.vbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
		w4.Position = 2;
		// Container child vbox4.Gtk.Box+BoxChild
		this.widlist1 = new global::TesteUnix.WidList ();
		this.widlist1.Events = ((global::Gdk.EventMask)(256));
		this.widlist1.Name = "widlist1";
		this.vbox4.Add (this.widlist1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.widlist1]));
		w5.Position = 3;
		this.Add (this.vbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button138.Clicked += new global::System.EventHandler (this.OnButton138Clicked);
		this.tree.CursorChanged += new global::System.EventHandler (this.OnTreeCursorChanged);
	}
}
